name: SmpCore
version: '${project.version}'
main: me.sirimperivm.spigot.Main
api-version: 1.19
depend:
  - Vault
softdepend:
  - PlaceholderAPI
authors:
  - SirImperivm_

commands:
  ga:
    aliases:
      - guildsadmin
  g:
    aliases:
      - guilds
  smpc:
    aliases:
      - smpcore