name: SmpCore
version: '${project.version}'
main: me.sirimperivm.spigot.Main
api-version: 1.19
loadbefore:
  - WorldGuard
depend:
  - Vault
  - WorldGuard
softdepend:
  - PlaceholderAPI
authors:
  - SirImperivm_

commands:
  ga:
    aliases:
      - guildsadmin
  g:
    aliases:
      - guilds
  smpc:
    aliases:
      - smpcore
  la:
    aliases:
      - livesadmin