settings:
  dbType: "mysql" # Questo può essere o mysql o mariadb
  database:
    host: "192.168.1.2"
    port: 3306
    username: "u20_4TdwERs6jC"
    password: "3PS2!8Ez@CQ2gW3QU@364gt7"
    dbname: "s20_SmpCore"
    tablePrefix: "smpc_"
  guilds:
    bank:
      startingBalance: 0.0
messages:
  prefixes:
    success: "&8[&a!&8] &7"
    info: "&8[&e!&8] &7"
    fail: "&8[&c!&8] &7"
  errors:
    no-perm:
      command: "%fpNecessiti del permesso &c$node &7per avere accesso a questo comando."
      action: "%fpNecessiti del permesso &c$node &7per eseguire quest'azione."
    no-console: "%fpComando accessibile solo dagli utenti in gioco."