settings:
  dbType: "mysql" # Questo può essere o mysql o mariadb
  database:
    host: "192.168.1.2"
    port: 3306
    username: "u44_D85VVtD94J"
    password: "Alnn^m8S!ghwst63p=IfrB!R"
    dbname: "s44_SmpCore"
    tablePrefix: "smpc_"
  guilds:
    bank:
      startingBalance: 0.0
      defaultBankLimit: 5000.0
  lobby:
    location:
      world: "null"
      posX: 0.0
      posY: 0.0
      posZ: 0.0
      rotYaw: 0.00
      rotPitch: 0.00
messages:
  prefixes:
    success: "&8[&a!&8] &7"
    info: "&8[&e!&8] &7"
    fail: "&8[&c!&8] &7"
  success:
    plugin:
      reloaded: "%spPlugin ricaricato con successo."
    guilds:
      created:
        - "&7✦»&m               &7¦✦¦&m               &7«✦"
        - "<GRADIENT:00AA00>&lGilda creata con successo</GRADIENT:00FF00>"
        - ""
        - "<SOLID:33DAFF>&lDati gilda:"
        - " &e✦ &6ID &8» &6$guildId"
        - " &e✦ &6GuildName &8» &6$guildName"
        - " &e✦ &6GuildTitle &8» &6$guildTitle"
        - " &e✦ &6Posizione &8» &6$position"
        - " &e✦ &6Limite Membri &8» &6$membersLimit"
        - " &e✦ &6Limite Banca &8» &6$bankLimit"
        - "&7✦»&m               &7¦✦¦&m               &7«✦"
      positionFormat: "$worldName&8,&6$posX&8,&6$posY&8,&6$posZ&8."
      deleted: "%spHai cancellato la gilda &a$guildName&7."
      add-member: "%spMembro aggiunto alla gilda &a$guildName&7."
      invites:
        accepted: "%spSei entrato nella gilda &a$guildName&7."
    lobby:
      located: "%spHai impostato correttamente la lobby."
  info:
    money:
      withdrawn: "%ip &e-&7$value."
    guild:
      deleted:
        sendToPlayer: "%ipLa tua gilda è stata rimossa dalla configurazione."
      members:
        invited:
          you: "%ipSei stato invitato a far parte della gilda &e$guildName&7. Hai 15 secondi per accettare con &e/g accept&7."
          members: "%ipL'utente &e$playerName&7 è stato invitato nella tua gilda."
    general:
      time:
        expired: "%ipTempo scaduto."
  errors:
    no-perm:
      command: "%fpNecessiti del permesso &c$node &7per avere accesso a questo comando."
      action: "%fpNecessiti del permesso &c$node &7per eseguire quest'azione."
    no-console: "%fpComando accessibile solo dagli utenti in gioco."
    guilds:
      alreadyExists: "%fpNel database è già presente una guild con questo nome."
      membersLimit:
        containsChars: "%fpNel limite di membri sono accettati solo numeri."
        greaterThanZero: "%fpIl limite di membri dev'essere superiore a 0."
      money:
        not-enough: "%fpNecessiti di &c$price&7 per acquistare la gilda $guildTitle&7."
      guildId:
        isNull: "%fpNon è stato impostato l'id della gilda relativo a questo slot."
        notExists: "%fpNon è stato trovato l'id della gilda relativo a questo slot."
      not-exists: "%fpNon esiste una gilda con questo nome."
      dont-have: "%fpNon sei membro di nessuna gilda."
      invites:
        not-received: "%fpNon hai ricevuto nessun invito."
    members:
      alreadyHaveGuild: "%fpHai già una gilda."
      target:
        is-on-a-guild: "%fpL'utente è già membro di una gilda."
        isnt-on-a-guild: "%fpL'utente non è membro di alcuna gilda."
        is-leader: "%fpL'utente è il leader di una gilda, non può essere espulso."
        isnt-a-guild-member: "%fpL'utente non è membro della tua gilda."
      limit-reached: "%fpHai raggiunto il limite massimo di utenti per la tua gilda &8(&c$membersLimit&8)&7."
    admin:
      limit-reached: "%fpQuesta gilda ha già raggiunto il limite di utenti."
    lobby:
      not-located: "%fpNon hai mai impostato lo spawn principale. &c(/ga setlobby)"
    players:
      not-found: "%fpUtente con questo nome non trovato."
permissions:
  admin-commands:
    core:
      main: smpc.admincommands.core.main
      reload: smpc.admincommands.core.reload
    guilds:
      main: smpc.admincommands.guilds.main
      setlobby: smpc.admincommands.guilds.setlobby
      create: smpc.admincommands.guilds.create
      delete: smpc.admincommands.guilds.delete
      addmember: smpc.admincommands.guilds.addmember
  user-commands:
    guilds:
      main: smpc.usercommands.guilds.main
      shop: smpc.usercommands.guilds.shop
      invite: smpc.usercommands.guilds.invite
      accept: smpc.usercommands.guilds.accept
      home: smpc.usercommands.guilds.home
      kick: smpc.usercommands.guilds.kick
  user-actions:
    guilds:
      shop:
        use: smpc.user.guilds.shop.use