settings:
  dbType: "mysql" # Questo può essere o mysql o mariadb
  database:
    host: "192.168.1.2"
    port: 3306
    username: "u44_D85VVtD94J"
    password: "Alnn^m8S!ghwst63p=IfrB!R"
    dbname: "s44_SmpCore"
    tablePrefix: "smpc_"
  guilds:
    bank:
      startingBalance: 0.0
      defaultBankLimit: -1.0
    costs:
      per-invite: 15000.0
  strings:
    valueFormatting:
      - '1000.0-k'
      - '1000000.0-m'
      - '1000000000.0-M'
      - '1000000000000.0-b'
      - '1000000000000000.0-B'
    valueFormatSize: 5
  programs:
    livesListener: true
  lives:
    defaultLivesCount: 5
    cantRespawnBlockedCommands:
      - "/warp"
      - "/spawn"
      - "/tpa"
      - "/tpaccept"
      - "/tpyes"
      - "/tpno"
  deathsManager:
    wins:
      money: 1500.0
    lose:
      money: 1500.0
messages:
  prefixes:
    success: "&8[&a!&8] &7"
    info: "&8[&e!&8] &7"
    fail: "&8[&c!&8] &7"
  success:
    plugin:
      reloaded: "%spPlugin ricaricato con successo."
    guilds:
      created:
        - "&9✦»&m               &9¦✦¦&m               &9«✦"
        - "<GRADIENT:00AA00>&lGilda creata con successo</GRADIENT:00FF00>"
        - ""
        - "<SOLID:33DAFF>&lDati gilda:"
        - " &e✦ &6ID &8» &6$guildId"
        - " &e✦ &6GuildName &8» &6$guildName"
        - " &e✦ &6GuildTitle &8» &6$guildTitle"
        - " &e✦ &6Posizione &8» &6$position"
        - " &e✦ &6Limite Membri &8» &6$membersLimit"
        - " &e✦ &6Limite Banca &8» &6$bankLimit"
        - "&9✦»&m               &9¦✦¦&m               &9«✦"
      positionFormat: "$worldName&8,&6$posX&8,&6$posY&8,&6$posZ&8."
      deleted: "%spHai cancellato la gilda &a$guildName&7."
      add-member: "%spMembro aggiunto alla gilda &a$guildName&7."
      remove-member: "%spMembro rimosso dalla gilda &a$guildName&7."
      invites:
        accepted: "%spSei entrato nella gilda &a$guildName&7."
      left: "%spSei uscito dalla tua gilda."
      spawn:
        relocated: "%fpSpawn per la gilda &a$guildName &7impostato alla tua zona."
    lobby:
      located: "%spHai impostato correttamente la lobby."
    officer:
      set: "%spHai promosso &a$username &7ad ufficiale nella tua gilda."
    deathZone:
      located: "%spDeathzone impostata correttamente."
  info:
    money:
      withdrawn: "%ip &e-&7$value."
      deposit: "%ip &e+&7$value."
    guild:
      deleted:
        sendToPlayer: "%ipLa tua gilda è stata rimossa dalla configurazione."
      members:
        invited:
          you: "%ipSei stato invitato a far parte della gilda &e$guildName&7. Hai 15 secondi per accettare con &e/g accept&7."
          members: "%ipL'utente &e$playerName&7 è stato invitato nella tua gilda."
        kicked: "%ipSei stato kickato dalla gilda."
        kicked-others: "%ipL'utente &e$player&7 è stato kickato dalla gilda."
        left: "%ipL'utente &e$player&7 è leftato dalla gilda."
        officer:
          set: "%ipSei stato promosso ad officer nella tua gilda."
          remove: "%ipSei stato degradato da officer a membro nella tua gilda."
        broadcast:
          officer:
            set: "%ipL'utente &e$username&7 è stato impostato come ufficiale della tua gilda."
            remove: "%ipL'utente &e$username&7 è stato degradato da ufficiale a membro nella tua gilda."
        leader:
          changed: "%ipPassaggio leader avvenuto nella tua gilda: &e$oldLeader &7-> &e$newLeader&7."
        admin:
          role:
            officer-set: "%ipUtente promosso con successo."
            member-set: "%ipUtente degradato con successo."
      money:
        taken: "%ip- &e€ $cost &7dalla banca della gilda."
        gave: "%ip+ &e€ $cost &7alla banca della gilda."
        admin:
          added-users: "%ipSono stati aggiunti &e€ $cost&7 dalla banca della gilda da un amministratore. Nuovo valore &e€ $guildBalance&7."
          added-admin: "%ipHai aggiunto &e€ $cost&7 dalla banca della gilda &e$guildName&7. Nuovo valore &e€ $guildBalance&7."
          taken-users: "%ipSono stati rimossi &e€ $cost&7 dalla banca della gilda da un amministratore. Nuovo valore &e€ $guildBalance&7."
          taken-admin: "%ipHai rimosso &e€ $cost&7 dalla banca della gilda &e$guildName&7. Nuovo valore &e€ $guildBalance&7."
          setted-users: "%ipLa banca della gilda è stata modificata da un amministratore. Nuovo valore &e€ $guildBalance&7."
          setted-admin: "%ipHai modificato la banca della gilda &e$guildName&7. Nuovo valore &e€ $guildBalance&7."
      bank:
        money:
          taken: "%ipL'utente &e$username&7 ha ritirato &e€ $value&7."
          deposit: "%ipL'utente &e$username&7 ha depositato &e€ $value&7."
        depositCooldown:
          startMessage: "%ipHai 15 secondi per scrivere in chat quanti soldi vuoi depositare."
        withdrawCooldown:
          startMessage: "%ipHai 15 secondi per scrivere in chat quanti soldi vuoi ritirare."
      chat:
        changed: "%ipChat impostata su &a$chatType&7."
        spy: "%ipChatSpy &e$status&7."
    lives:
      members:
        death:
          can-respawn: "%ipSei morto, hai perso &e1 &7vita, rimanenti &e$livesCount&7."
          cant-respawn: "%ipSei morto, hai perso tutte le tue vite, non potrai rigiocare."
          respawn-in: "%ipRespawnerai tra &e5 &7secondi."
      life:
        added:
          user: "%ipHai ricevuto &e$livesCount&7 vite al tuo account, totale &e$totalCount&7."
          admin: "%ipHai aggiunto &e$livesCount&7 vite all'utente &e$playerName&7."
        taken:
          user: "%ipSono state rimosse &e$livesCount&7 vite dal tuo account, totale &e$totalCount&7."
          admin: "%ipHai rimosso &e$livesCount&7 vite all'utente &e$playerName&7."
    bounties:
      set:
        broadcast:
          fromPlayer:
            - "&8»»»» &c&lNuova Taglia &8««««"
            - "&6Esecutore &8» &6$executorName"
            - "&6Bersaglio &8» &6$targetName"
            - "&6Guadagno &8» &6€$bountyValue"
            - "&8»»»» &c&lNuova Taglia &8««««"
          fromAdmin:
            - "&8»»»» &c&lNuova Taglia &8««««"
            - "&6Esecutore &8» &6Sistema"
            - "&6Bersaglio &8» &6$targetName"
            - "&6Guadagno &8» &6€$bountyValue"
            - "&8»»»» &c&lNuova Taglia &8««««"
      removed:
        broadcast:
          - "&8»»»» &c&lTaglia Rimossa &8««««"
          - "&6Ex Bersaglio &8» &6$targetName"
          - "&8»»»» &c&lTaglia Rimossa &8««««"
      obtained:
        broadcast:
          - "&8»»»» &c&lTaglia Ottenuta &8««««"
          - "&6Ex Bersaglio &8» &6$targetName"
          - "&8»»»» &c&lTaglia Ottenuta &8««««"
    general:
      time:
        expired: "%ipTempo scaduto."
  errors:
    no-perm:
      command: "%fpNecessiti del permesso &c$node &7per avere accesso a questo comando."
      action: "%fpNecessiti del permesso &c$node &7per eseguire quest'azione."
    no-console: "%fpComando accessibile solo dagli utenti in gioco."
    guilds:
      alreadyExists: "%fpNel database è già presente una guild con questo nome."
      membersLimit:
        containsChars: "%fpNel limite di membri sono accettati solo numeri."
        greaterThanZero: "%fpIl limite di membri dev'essere superiore a 0."
      money:
        not-enough: "%fpNecessiti di &c$price&7 per acquistare la gilda $guildTitle&7."
        guild:
          invites:
            not-enough-money: "%fpLa gilda deve possedere &c$cost &7per poter invitare nuovi membri."
            not-enough-after: "%fpLa gilda attuale non possiede più &c$cost &7perciò l'utente &c$username&7 non può accettare l'invito."
      guildId:
        isNull: "%fpNon è stato impostato l'id della gilda relativo a questo slot."
        notExists: "%fpNon è stato trovato l'id della gilda relativo a questo slot."
      not-exists: "%fpNon esiste una gilda con questo nome."
      dont-have: "%fpNon sei membro di nessuna gilda."
      invites:
        not-received: "%fpNon hai ricevuto nessun invito."
      region:
        entering: "%fpNon sei membro di questa gilda, non puoi entrare."
      bank:
        deposit:
          already-withdrawing: "%fpSe stai ritirando dei soldi nello stesso momento non puoi depositarne alcuni."
          limit-reached: "%fpIl limite di deposito in questa gilda è &c€ $depositLimit&7."
          not-enough-money: "%fpNon hai abbastanza soldi da depositare."
        withdraw:
          already-depositing: "%fpSe stai depositando dei soldi nello stesso momento non puoi ritirarne alcuni."
          bank-not-enough: "%fpLa banca della gilda non dispone di tale quantità."
        chars-not-allowed: "%fpIn questa sezione sono validi solamente i numeri."
      chat:
        no-member-reached: "%fpNon è stato possibile recapitare il messaggio."
      upgrades:
        requirements:
          level:
            too-low: "%fpLa gilda non soddisfa i requisiti relativi al livello."
            too-high: "%fpLa gilda ha un livello superiore a quello richiesto."
          money:
            not-enough: "%fpPer ottenere questo livello la gilda necessita di &c€ $cost&7."
      already-bought: "%fpLa gilda è già stata acquistata."
      not-exist: "%fpLa gilda non esiste."
      chars-not-allowed: "%fpDevi inserire un numero."
    members:
      alreadyHaveGuild: "%fpHai già una gilda."
      target:
        is-on-a-guild: "%fpL'utente è già membro di una gilda."
        isnt-on-a-guild: "%fpL'utente non è membro di alcuna gilda."
        is-leader: "%fpL'utente è il leader di una gilda, non può essere espulso."
        isnt-leader: "%fpNon sei leader della tua gilda."
        isnt-a-guild-member: "%fpL'utente non è membro della tua gilda."
      limit-reached: "%fpHai raggiunto il limite massimo di utenti per la tua gilda &8(&c$membersLimit&8)&7."
      leader:
        cant-leave: "%fpIl leader della gilda non può uscire prima di dare la leadership a qualcun'altro. &8(&c/g newleadership <membro>&8)"
      officer:
        already: "%fpL'utente &c$username&7 è già ufficiale nella tua gilda."
        isnt: "%fpL'utente &c$username&7 non è ufficiale nella tua gilda."
    admin:
      limit-reached: "%fpQuesta gilda ha già raggiunto il limite di utenti."
      members:
        target:
          role-not-found: "%fpIl ruolo scelto non è valido, scegli tra (officer e member)."
          is-already-officer: "%fpL'utente è già ufficiale nella sua gilda."
          is-already-member: "%fpL'utente è già membro nella sua gilda."
    lobby:
      not-located: "%fpNon hai mai impostato lo spawn principale. &c(/ga setlobby)"
    players:
      not-found: "%fpUtente con questo nome non trovato."
    lives:
      deathZone:
        not-located: "%fpNon è stato impostato lo spawn della deathzone, è richiesta una segnalazione allo staff."
      contains-chars: "%fpIn questa sezione è solo possibile usare numeri."
      commandBlocked: "%fpSei morto, non puoi eseguire questo comando."
    bounties:
      chars-not-allowed: "%fpIn questa sezione è possibile inserire solamente numeri."
      money:
        not-enough: "%fpNon hai abbastanza soldi."
      target:
        cant-be-yourself: "%fpNon puoi impostarti una taglia da solo."
        hasnt-bounty: "%fpL'utente non ha una taglia."
  others:
    guilds:
      chat: "&a[GC] &f $guildRole $playerName &8» &f$message"
      chat-spy: "&6[SPY] $guildTitle&r $guildRole $playerName &8» &f$message"
      list:
        admin:
          header: "&c✦»&m               &c¦✦¦&m               &c«✦"
          title: "&eLista Gilde:"
          spacer: "&r"
          lines:
            header: "<SOLID:007FFF>GuildName   Acquisto   Membri"
            line: "$guildName   $boughtStats   $guildMembers"
          footer: "&c✦»&m               &c¦✦¦&m               &c«✦"
        user:
          header: "&9✦»&m               &9¦✦¦&m               &9«✦"
          title: "&eLista Gilde:"
          spacer: "&r"
          lines:
            header: "<SOLID:007FFF>GuildName   Acquisto   Membri"
            line: "$guildName   $boughtStats   $guildMembers"
          footer: "&9✦»&m               &9¦✦¦&m               &9«✦"
      guild-info:
        user:
          - "&5✦»&m               &5¦✦¦&m               &5«✦"
          - "<SOLID:008080>Info Gilda $guildTitle"
          - ""
          - "<SOLID:960018>Info di base:"
          - " &b✦ &fCapoGilda &8» &f$guildLeader"
          - " &b✦ &fMembri &8» &f$membersCount&8/&f$membersLimit"
          - " &b✦ &fSoldi &8» &f$bankBalance"
          - " &b✦ &fLivello &8» &f$guildLevel"
          - ""
          - "<SOLID:960018>Membri per ruolo:"
          - " &c✦ &fOfficers &8» &f$officersCount"
          - " &c✦ &fGildani &8» &f$guildersCount"
          - ""
          - "$officersOnline"
          - "$guildersOnline"
          - "&5✦»&m               &5¦✦¦&m               &5«✦"
        admin:
          - "&5✦»&m               &5¦✦¦&m               &5«✦"
          - "<SOLID:008080>Info Gilda $guildTitle"
          - ""
          - "<SOLID:960018>Info di base:"
          - " &b✦ &fCapoGilda &8» &f$guildLeader"
          - " &b✦ &fMembri &8» &f$membersCount&8/&f$membersLimit"
          - " &b✦ &fSoldi &8» &f$bankBalance"
          - " &b✦ &fLivello &8» &f$guildLevel"
          - " &b✦ &fGuildId &8» &f$guildId"
          - ""
          - "<SOLID:960018>Membri per ruolo:"
          - " &c✦ &fOfficers &8» &f$officersCount"
          - " &c✦ &fGildani &8» &f$guildersCount"
          - ""
          - "$officersOnline"
          - "$guildersOnline"
          - "&5✦»&m               &5¦✦¦&m               &5«✦"
          - "$guildCopyId"
        general:
          online-officers:
            format-prefix: "&6Officers Online: "
            userformat: "&f$username"
            commas: "&6, "
          online-guilders:
            format-prefix: "&5Gildani Online: "
            userformat: "&f$username"
            commas: "&5, "
      top:
        bank:
          header: "&6✦»&m               &6¦✦¦&m               &6«✦"
          title: "<SOLID:f39f18>Top Bilanci Gilde"
          spacer: "&r"
          lines:
            header: "&cNome   Soldi"
            line: "$guildTitle   &f$guildBalance"
          footer: "&6✦»&m               &6¦✦¦&m               &6«✦"
        members:
          header: "&2✦»&m               &2¦✦¦&m               &2«✦"
          title: "<SOLID:66ff66>Top Membri Gilde"
          spacer: "&r"
          lines:
            header: "&cNome   Membri"
            line: "$guildTitle   &f$membersCount"
          footer: "&2✦»&m               &2¦✦¦&m               &2«✦"
    lives:
      top:
        header: "&7|----------|&e✦&7|----------|"
        title: "&dTop Vite"
        spacer: "&r"
        lines:
          header: "&5Nome   Vite"
          line: "$playerName $livesCount"
        footer: "&7|----------|&e✦&7|----------|"
      info:
        - "&2✦»&m               &2¦✦¦&m               &2«✦"
        - "&aL'utente &b$playerName &aha &b$livesCount &avite."
        - "&2✦»&m               &2¦✦¦&m               &2«✦"
    deaths:
      placeholderFormats:
        dead: "[Morto]"
        live: ""
      message:
        by-null: "&c✖ &7L'utente &c$victim&7 è morto. &c✖"
        by-player: "&c✖ &7L'utente &c$killer&7 ha ucciso &c$victim&7. &c✖"
    bounties:
      placeholderFormats:
        bounty: "&6B:&7€&f$bountyValue"
placeholders:
  guilds:
    name: guild_name # Il placeholder relativo è %smpc_guild_name%
    id: guild_id # Il placeholder relativo è %smpc_guild_id%
    title: guild_title # Il placeholder relativo è %smpc_guild_title%
    bank:
      still: guild_bank_balance # Il placeholder relativo è %smpc_guild_bank_balance%
      formatted: guild_bank_balance-formatted # Il placeholder relativo è %smpc_guild_bank_balance-formatted%
    roles:
      guilders-count: guild_guilders-count # Il placeholder rleativo è %smpc_guild_guilders-count%
      officers-count: guild_officers-count # Il placeholder rleativo è %smpc_guild_officers-count%
    members:
      count: guild_members-count #  Il placeholder rleativo è %smpc_guild_members-count%
      limit: guild_members-limit #  Il placeholder rleativo è %smpc_guild_members-limit%
  lives:
    count: lives_count # Il placeholder relativo è %smpc_lives_count%
    is_dead: lives_deaths_is_dead # Il placeholder relativo è %smpc_deaths_is_dead%
  deathsManager:
    deaths_count: deathsmanager_deaths_count # Il placeholder relativo è %smpc_deathsmanager_deaths_count%
    deaths_count-formatted: deathsmanager_deaths_count-formatted # Il placeholder relativo è %smpc_deathsmanager_deaths_count-formatted%
    kills_count: deathsmanager_kills_count # Il placeholder relativo è %smpc_deathsmanager_kills_count%
    kills_count-formatted: deathsmanager_kills_count-formatted # Il placeholder relativo è %smpc_deathsmanager_kills_count-formatted%
  bounties:
    value: bounties_value # Il placeholder relativo è %smpc_bounties_value%
    value-formatted: bounties_value-formatted # Il placeholder relativo è %smpc_bounties_value-formatted%
permissions:
  admin-commands:
    core:
      main: smpc.admincommands.core.main
      reload: smpc.admincommands.core.reload
    guilds:
      main: smpc.admincommands.guilds.main
      setlobby: smpc.admincommands.guilds.setlobby
      create: smpc.admincommands.guilds.create
      delete: smpc.admincommands.guilds.delete
      addmember: smpc.admincommands.guilds.addmember
      deletemember: smpc.admincommands.guilds.deletemember
      changerole: smpc.admincommands.guilds.changerole
      list: smpc.admincommands.guilds.list
      info: smpc.admincommands.guilds.info
      changespawn: smpc.admincommands.guilds.changespawn
      money:
        use: smpc.admincommands.guilds.money.use
        take: smpc.admincommands.guilds.money.take
        give: smpc.admincommands.guilds.money.give
        set: smpc.admincommands.guilds.money.set
    lives:
      main: smpc.admincommands.lives.main
      info: smpc.admincommands.lives.info
      setdeathzone: smpc.admincommands.lives.setdeathzone
      life:
        give: smpc.admincommands.lives.live.give
        take: smpc.admincommands.lives.live.take
      top: smpc.admincommands.lives.top
    bounties:
      main: smpc.admincommands.bounty.main
      set: smpc.admincommands.bounty.set
      remove: smpc.admincommands.bounty.remove
  user-commands:
    guilds:
      main: smpc.usercommands.guilds.main
      shop: smpc.usercommands.guilds.shop
      invite: smpc.usercommands.guilds.invite
      accept: smpc.usercommands.guilds.accept
      home: smpc.usercommands.guilds.home
      kick: smpc.usercommands.guilds.kick
      leave: smpc.usercommands.guilds.leave
      chat: smpc.usercommands.guilds.chat
      bank: smpc.usercommands.guilds.bank
      list: smpc.usercommands.guilds.list
      info: smpc.usercommands.guilds.info
      top-bank: smpc.usercommands.guilds.top-bank
      top-members: smpc.usercommands.guilds.top-members
      newleadership: smpc.usercommands.guilds.newleadership
      upgrades: smpc.usercommands.guilds.upgrades
      officer:
        main: smpc.usercommands.guilds.officers.use
        set: smpc.usercommands.guilds.officers.use
        remove: smpc.usercommands.guilds.officers.use
    lives:
      main: smpc.usercommands.lives.main
      get:
        user: smpc.usercommands.lives.get
        others: smpc.usercommands.lives.get.others
    bounties:
      main: smpc.usercommands.bounties.main
      set: smpc.usercommands.bounties.set
  user-actions:
    guilds:
      shop:
        use: smpc.user.guilds.shop.use
      bank:
        use: smpc.user.guilds.bank.use
        deposit: smpc.user.guilds.bank.deposit
        withdraw: smpc.user.guilds.bank.withdraw
      upgrades:
        use: smpc.user.guilds.upgrades.use
  admin-actions:
    guilds:
      entering:
        bypass: smpc.user.guilds.bypass
      chat:
        spy: smpc.user.guilds.chat.spy
    lives:
      blockedCommands:
        bypass: smpc.user.lives.block.bypass