settings:
  dbType: "mysql" # Questo può essere o mysql o mariadb
  database:
    host: "192.168.1.2"
    port: 3306
    username: "u44_mJ9FTgrleX"
    password: "CTS+0i5CH7pu+Gdq3iLuy=sj"
    dbname: "s44_SmpCore"
    tablePrefix: "smpc_"
  guilds:
    bank:
      startingBalance: 0.0
      defaultBankLimit: 5000.0
messages:
  prefixes:
    success: "&8[&a!&8] &7"
    info: "&8[&e!&8] &7"
    fail: "&8[&c!&8] &7"
  success:
    plugin:
      reloaded: "%spPlugin ricaricato con successo."
    guilds:
      created:
        - "&7✦»&m               &7¦✦¦&m               &7«✦"
        - "<GRADIENT:00AA00>&lGilda creata con successo</GRADIENT:00FF00>"
        - ""
        - "<SOLID:33DAFF>&lDati gilda:"
        - " &e✦ &6ID &8» &6$guildId"
        - " &e✦ &6GuildName &8» &6$guildName"
        - " &e✦ &6GuildTitle &8» &6$guildTitle"
        - " &e✦ &6Posizione &8» &6$position"
        - " &e✦ &6Limite Membri &8» &6$membersLimit"
        - " &e✦ &6Limite Banca &8» &6$bankLimit"
        - "&7✦»&m               &7¦✦¦&m               &7«✦"
      positionFormat: "$worldName&8,&6$posX&8,&6$posY&8,&6$posZ&8."
  errors:
    no-perm:
      command: "%fpNecessiti del permesso &c$node &7per avere accesso a questo comando."
      action: "%fpNecessiti del permesso &c$node &7per eseguire quest'azione."
    no-console: "%fpComando accessibile solo dagli utenti in gioco."
    guilds:
      alreadyExists: "%fpNel database è già presente una guild con questo nome."
      membersLimit:
        containsChars: "%fpNel limite di membri sono accettati solo numeri."
        greaterThanZero: "%fpIl limite di membri dev'essere superiore a 0."
permissions:
  admin-commands:
    core:
      main: smpc.admincommands.core.main
      reload: smpc.admincommands.core.reload
    guilds:
      main: smpc.admincommands.guilds.main
      create: smpc.admincommands.guilds.create
  user-commands:
    guilds:
      main: smpc.usercommands.guilds.main
      shop: smpc.usercommands.guilds.shop